cloud:
  aws:
    credentials:
      access-key: AKIAWVACLL6BZV443NI3
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: hmsphotos


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090